server:
  servlet:
    context-path: /
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event_db?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=GMT-3
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  jackson:
    default-property-inclusion: non_null
  application:
    name: agendacultural